Simplify notifications and implement multiple telegram channels
bcc-code/bcc-media-flows pull request #222
Opened 2024-04-16 12:30 UTC by KillerX

* Removed the `notificationService` concept
* Removed the `notifications.Target` concept -> You have to send emails and telegram messages separately
* Added support for multiple channels
* The util functions for notifications now log errors but don't return them as they were generally ignored

Fixes https://github.com/bcc-code/bcc-media-flows/issues/204

2024-04-16 14:33 UTC, andreasgangso reviewed
I think the abstractions that was there was good conceptually, but since we still haven't really had a use for it yet I agree to remove it. We can always add it back later.

2024-04-16 14:33 UTC, andreasgangso commented on utils/workflows/files.go
> +		NotifyTelegramChannel(ctx, telegram.ChatOslofjord, fmt.Sprintf("⚠️ File ```%s``` already exists, retrying in one minute (%d/%d)", file.Rclone(), i, retries))
maybe not

2024-04-16 14:34 UTC, andreasgangso requested changes
see above files.go

2024-04-17 12:21 UTC, KillerX commented on utils/workflows/files.go
> +		NotifyTelegramChannel(ctx, telegram.ChatOslofjord, fmt.Sprintf("⚠️ File ```%s``` already exists, retrying in one minute (%d/%d)", file.Rclone(), i, retries))
Fixed in See #224

2024-04-17 12:45 UTC, merged