feat(transcode-workflow): implement the preview transcoder
bcc-code/bcc-media-flows pull request #6
Opened 2023-08-16 10:29 UTC by fredrikved

2023-08-16 11:36 UTC, andreasgangso reviewed
Love how simple it is to read and follow

2023-08-17 09:08 UTC, KillerX requested changes
I think we need to support audio only as well.
Have actually never tested image only.

2023-08-17 09:08 UTC, KillerX commented on services/transcode/preview.go
> +func Preview(input PreviewInput, progressCallback func(float64)) (*PreviewResult, error) {
How does this react if it gets fed a audio file?
Here is a sample of what I used to encode audio only tracks:

```
ffmpeg -hide_banner -loglevel +level -y -ss 0.0 -i /path/to/filename.wav -filter_complex sws_flags=bicubic;[0:a:0]asplit=1[AUDIO-main-.mp4-0];[AUDIO-main-.mp4-0]aformat=channel_layouts=stereo[AUDIO-.mp4-0] -map [AUDIO-.mp4-0] -vn -c:a:0 aac -ar:a:0 44100 -b:a:0 128k /path/to/result.mp4
```

2023-08-17 09:52 UTC, KillerX approved these changes

2023-08-17 09:55 UTC, merged