Refactoring
bcc-code/bcc-media-flows pull request #61
Opened 2023-09-27 11:13 UTC by fredrikved

Started with some refactoring.

2023-09-27 16:56 UTC, andreasgangso requested changes
Kan hende git hadde maintaina history bedre her hvis man gjorde ting i 2 commits?
Se 1 kommentar på den ene eventen.

Ellers LGTM 👍

2023-09-27 16:56 UTC, andreasgangso commented on workflows/export/asset_export-vx.go
> +	err = wfutils.PublishEvent(ctx, "asset.delivered", map[string]string{
`github.com/bcc-code/bcc-media-platform/backend/events.AssetDelivered`

2023-09-27 18:52 UTC, fredrikved commented
Will split into separate commits the next time I move things across packages.

2023-09-28 05:55 UTC, KillerX approved these changes

2023-09-28 05:55 UTC, KillerX commented on utils/wfutils/files.go
> +package wfutils
I keep reading this as `wtfutils` XD

2023-09-28 05:55 UTC, KillerX commented on utils/wfutils/files.go
> +	path := fmt.Sprintf("%s/%04d/%02d/%02d/%s", utils.GetIsilonPrefix()+"/Production/aux", date.Year(), date.Month(), date.Day(), info.OriginalRunID)
Maybe we need the ability to switch out the `aux` part. Right now this is the correct place for many things but others are coming.

2023-09-28 05:55 UTC, KillerX commented on workflows/export/asset_export-vx.go
Is there some logic for mixing `_` and `-` in file names?

2023-09-28 07:19 UTC, andreasgangso approved these changes

2023-09-28 07:24 UTC, merged