feat: add R128 based linear normalization
bcc-code/bcc-media-flows pull request #62
Opened 2023-09-27 14:12 UTC by KillerX

2023-09-27 14:26 UTC, fredrikved commented on utils/execute_command.go
> +func ExecuteAnalysisCmd(cmd *exec.Cmd, outputCallback func(string)) (string, error) {
This analysis can take time as well (for meetings, etc). Wouldn't piping progress to another pipe be better?

2023-09-28 09:45 UTC, andreasgangso requested changes

2023-09-28 09:45 UTC, andreasgangso commented on activities/normalize.go
> +	IntegratedLoudnes   float64
IntegratedLoudness

2023-09-28 09:45 UTC, andreasgangso commented on activities/normalize.go
> +	LoudnesRange        float64
LoudnessRange

2023-09-28 09:45 UTC, andreasgangso commented on services/ffmpeg/ebur128.go
> +	InputIntegratedLoudnes string `json:"input_i"`
Loudness

2023-09-28 09:45 UTC, andreasgangso commented on activities/normalize.go
> +		OutFilePath: res.OutputPath,
Maybe reuse the LinearNormalizeAudio result type (AudioResult)
to decrease the amount of types and mappings

2023-09-28 09:45 UTC, andreasgangso commented on activities/normalize.go
> +type AnalyzeEBUR128Result struct {
Maybe reuse this result type (move it to common?), because it's duplicated three times now

2023-09-28 10:28 UTC, fredrikved approved these changes

2023-09-28 10:28 UTC, fredrikved commented on services/transcode/linear_normalize.go
> +	//replace output extension to .aac
inaccurate comment?

2023-09-28 10:30 UTC, andreasgangso requested changes

2023-09-28 10:30 UTC, andreasgangso commented on services/transcode/linear_normalize.go
> +func LinearNormalizeAudio(input common.AudioInput, adjustment float64, cb ffmpeg.ProgressCallback) (*common.AudioResult, error) {
denne funksjonen gjør ikke normalization så LinearAdjustAudio er bedre

2023-09-28 10:57 UTC, andreasgangso approved these changes

2023-09-28 11:22 UTC, merged